# Generated by Django 5.2.6 on 2025-09-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_callrecord_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="callrecord",
            name="suggestion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
